//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireAxe.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FireAxe.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About FireAxe.
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;re problems in subitems..
        /// </summary>
        public static string AddonChildProblemExplain {
            get {
                return ResourceManager.GetString("AddonChildProblemExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The corresponding file &quot;{0}&quot; doesn&apos;t exist..
        /// </summary>
        public static string AddonFileNotExistProblemExplain {
            get {
                return ResourceManager.GetString("AddonFileNotExistProblemExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The strategy of enablement of the group is not applied correctly..
        /// </summary>
        public static string AddonGroupEnableStrategyProblemExplain {
            get {
                return ResourceManager.GetString("AddonGroupEnableStrategyProblemExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The addon {0} denied the move or renaming. There may be ongoing tasks(like download tasks). Please try again later..
        /// </summary>
        public static string AddonMoveDeniedMessage {
            get {
                return ResourceManager.GetString("AddonMoveDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tag.
        /// </summary>
        public static string AddTag {
            get {
                return ResourceManager.GetString("AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tool for managing Left 4 Dead 2 addons..
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Tags from Workshop.
        /// </summary>
        public static string ApplyTagsFromWorkshop {
            get {
                return ResourceManager.GetString("ApplyTagsFromWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string AuthorColon {
            get {
                return ResourceManager.GetString("AuthorColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is detected that you copied a workshop item link ({0}). Would you like to create a workshop addon?.
        /// </summary>
        public static string AutoDetectWorkshopItemLinkDialogMessage {
            get {
                return ResourceManager.GetString("AutoDetectWorkshopItemLinkDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto detect workshop item link in Clipboard.
        /// </summary>
        public static string AutoDetectWorkshopItemLinkInClipboard {
            get {
                return ResourceManager.GetString("AutoDetectWorkshopItemLinkInClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto redownload items.
        /// </summary>
        public static string AutoRedownload {
            get {
                return ResourceManager.GetString("AutoRedownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the Name Automatically.
        /// </summary>
        public static string AutoSetName {
            get {
                return ResourceManager.GetString("AutoSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Update Strategy.
        /// </summary>
        public static string AutoUpdateStrategy {
            get {
                return ResourceManager.GetString("AutoUpdateStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Move.
        /// </summary>
        public static string CancelMove {
            get {
                return ResourceManager.GetString("CancelMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Refreshing.
        /// </summary>
        public static string CancelRefreshing {
            get {
                return ResourceManager.GetString("CancelRefreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t move the item &quot;{0}&quot;!.
        /// </summary>
        public static string CantMoveItemWithName {
            get {
                return ResourceManager.GetString("CantMoveItemWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check all addons to keep their status up to date..
        /// </summary>
        public static string CheckAllTip {
            get {
                return ResourceManager.GetString("CheckAllTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string CheckingForUpdatesMessage {
            get {
                return ResourceManager.GetString("CheckingForUpdatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear caches of all addons..
        /// </summary>
        public static string ClearAllCachesTip {
            get {
                return ResourceManager.GetString("ClearAllCachesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Caches.
        /// </summary>
        public static string ClearCaches {
            get {
                return ResourceManager.GetString("ClearCaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Directory.
        /// </summary>
        public static string CloseDirectory {
            get {
                return ResourceManager.GetString("CloseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection ID.
        /// </summary>
        public static string CollectionId {
            get {
                return ResourceManager.GetString("CollectionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Theme.
        /// </summary>
        public static string ColorTheme {
            get {
                return ResourceManager.GetString("ColorTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected items? This cannot be undone. .
        /// </summary>
        public static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected tags completely?.
        /// </summary>
        public static string ConfirmDeleteTagCompletely {
            get {
                return ResourceManager.GetString("ConfirmDeleteTagCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game path &quot;{0}&quot; found. Are you sure you want to use this path?.
        /// </summary>
        public static string ConfirmFoundGamePathMessage {
            get {
                return ResourceManager.GetString("ConfirmFoundGamePathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to ignore all the conflicting files? .
        /// </summary>
        public static string ConfirmIgnoreAllConflictingFiles {
            get {
                return ResourceManager.GetString("ConfirmIgnoreAllConflictingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher version of files are opening. This will cause file information loss. Are you sure you want to continue?.
        /// </summary>
        public static string ConfirmOpenHigherVersionFileMessage {
            get {
                return ResourceManager.GetString("ConfirmOpenHigherVersionFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all the conflict ignoring files?.
        /// </summary>
        public static string ConfirmRemoveAllConflictIgnoringFiles {
            get {
                return ResourceManager.GetString("ConfirmRemoveAllConflictIgnoringFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict Ignoring Files.
        /// </summary>
        public static string ConflictIgnoringFiles {
            get {
                return ResourceManager.GetString("ConflictIgnoringFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting Addons.
        /// </summary>
        public static string ConflictingAddons {
            get {
                return ResourceManager.GetString("ConflictingAddons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting Details.
        /// </summary>
        public static string ConflictingDetails {
            get {
                return ResourceManager.GetString("ConflictingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting Files.
        /// </summary>
        public static string ConflictingFiles {
            get {
                return ResourceManager.GetString("ConflictingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FireAxe crashed due to an unhandled exception. The following is the details of the exception:.
        /// </summary>
        public static string CrashReporterMessageHeader {
            get {
                return ResourceManager.GetString("CrashReporterMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the collection. Please try again..
        /// </summary>
        public static string CreateCollectionFailedMessage {
            get {
                return ResourceManager.GetString("CreateCollectionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Time: .
        /// </summary>
        public static string CreationTimeColon {
            get {
                return ResourceManager.GetString("CreationTimeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current version is latest..
        /// </summary>
        public static string CurrentVersionLatestMessage {
            get {
                return ResourceManager.GetString("CurrentVersionLatestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Preview Image.
        /// </summary>
        public static string CustomizePreviewImage {
            get {
                return ResourceManager.GetString("CustomizePreviewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete And Retain Files.
        /// </summary>
        public static string DeleteAndRetainFile {
            get {
                return ResourceManager.GetString("DeleteAndRetainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Completely.
        /// </summary>
        public static string DeleteCompletely {
            get {
                return ResourceManager.GetString("DeleteCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Redundant VPK files.
        /// </summary>
        public static string DeleteRedundantVpkFiles {
            get {
                return ResourceManager.GetString("DeleteRedundantVpkFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Include tags in all addons).
        /// </summary>
        public static string DeleteTagCompletelyTip {
            get {
                return ResourceManager.GetString("DeleteTagCompletelyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string DescriptionColon {
            get {
                return ResourceManager.GetString("DescriptionColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Recursively (including all subitems).
        /// </summary>
        public static string DisableRecursively {
            get {
                return ResourceManager.GetString("DisableRecursively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not open the directory &quot;left4dead2/addons&quot;..
        /// </summary>
        public static string DontOpenGameAddonsDirectory {
            get {
                return ResourceManager.GetString("DontOpenGameAddonsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download List.
        /// </summary>
        public static string DownloadList {
            get {
                return ResourceManager.GetString("DownloadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled/Disabled.
        /// </summary>
        public static string EnabledOrDisabled {
            get {
                return ResourceManager.GetString("EnabledOrDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Recursively (including all subitems).
        /// </summary>
        public static string EnableRecursively {
            get {
                return ResourceManager.GetString("EnableRecursively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy of Enablement.
        /// </summary>
        public static string EnableStrategy {
            get {
                return ResourceManager.GetString("EnableStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Enum_AddonGroupEnableStrategy_All {
            get {
                return ResourceManager.GetString("Enum_AddonGroupEnableStrategy_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Enum_AddonGroupEnableStrategy_None {
            get {
                return ResourceManager.GetString("Enum_AddonGroupEnableStrategy_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Enum_AddonGroupEnableStrategy_Single {
            get {
                return ResourceManager.GetString("Enum_AddonGroupEnableStrategy_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Single.
        /// </summary>
        public static string Enum_AddonGroupEnableStrategy_SingleRandom {
            get {
                return ResourceManager.GetString("Enum_AddonGroupEnableStrategy_SingleRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid View.
        /// </summary>
        public static string Enum_AddonNodeListItemViewKind_Grid {
            get {
                return ResourceManager.GetString("Enum_AddonNodeListItemViewKind_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Tile View.
        /// </summary>
        public static string Enum_AddonNodeListItemViewKind_LargeTile {
            get {
                return ResourceManager.GetString("Enum_AddonNodeListItemViewKind_LargeTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile View.
        /// </summary>
        public static string Enum_AddonNodeListItemViewKind_MediumTile {
            get {
                return ResourceManager.GetString("Enum_AddonNodeListItemViewKind_MediumTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Tile View.
        /// </summary>
        public static string Enum_AddonNodeListItemViewKind_SmallTile {
            get {
                return ResourceManager.GetString("Enum_AddonNodeListItemViewKind_SmallTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by Creation Time.
        /// </summary>
        public static string Enum_AddonNodeSortMethod_CreationTime {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by State.
        /// </summary>
        public static string Enum_AddonNodeSortMethod_EnableState {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_EnableState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by File Creation Time.
        /// </summary>
        public static string Enum_AddonNodeSortMethod_FileCreationTime {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_FileCreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by File Size.
        /// </summary>
        public static string Enum_AddonNodeSortMethod_FileSize {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by Name.
        /// </summary>
        public static string Enum_AddonNodeSortMethod_Name {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Sort.
        /// </summary>
        public static string Enum_AddonNodeSortMethod_None {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by Priority.
        /// </summary>
        public static string Enum_AddonNodeSortMethod_Priority {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by Global Priority.
        /// </summary>
        public static string Enum_AddonNodeSortMethod_PriorityInHierarchy {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_PriorityInHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by Problem Count.
        /// </summary>
        public static string Enum_AddonNodeSortMethod_ProblemCount {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_ProblemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by Tags.
        /// </summary>
        public static string Enum_AddonNodeSortMethod_Tag {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string Enum_AddonTagFilterMode_And {
            get {
                return ResourceManager.GetString("Enum_AddonTagFilterMode_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not.
        /// </summary>
        public static string Enum_AddonTagFilterMode_Not {
            get {
                return ResourceManager.GetString("Enum_AddonTagFilterMode_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Enum_AddonTagFilterMode_Or {
            get {
                return ResourceManager.GetString("Enum_AddonTagFilterMode_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Enum_AppColorTheme_Dark {
            get {
                return ResourceManager.GetString("Enum_AppColorTheme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Enum_AppColorTheme_Default {
            get {
                return ResourceManager.GetString("Enum_AppColorTheme_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Enum_AppColorTheme_Light {
            get {
                return ResourceManager.GetString("Enum_AppColorTheme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Enum_AutoUpdateStrategy_Default {
            get {
                return ResourceManager.GetString("Enum_AutoUpdateStrategy_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Enum_AutoUpdateStrategy_Disabled {
            get {
                return ResourceManager.GetString("Enum_AutoUpdateStrategy_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enum_AutoUpdateStrategy_Enabled {
            get {
                return ResourceManager.GetString("Enum_AutoUpdateStrategy_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred during the operation!.
        /// </summary>
        public static string ExceptionOccurMessage {
            get {
                return ResourceManager.GetString("ExceptionOccurMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the latest version..
        /// </summary>
        public static string FailedToGetLatestVersion {
            get {
                return ResourceManager.GetString("FailedToGetLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites: .
        /// </summary>
        public static string FavoritesColon {
            get {
                return ResourceManager.GetString("FavoritesColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file download is uncompleted!.
        /// </summary>
        public static string FileDownloadUncompleted {
            get {
                return ResourceManager.GetString("FileDownloadUncompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size: .
        /// </summary>
        public static string FileSizeColon {
            get {
                return ResourceManager.GetString("FileSizeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter is enabled.
        /// </summary>
        public static string FilterEnabledMessage {
            get {
                return ResourceManager.GetString("FilterEnabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find from Directory.
        /// </summary>
        public static string FindFromDirectory {
            get {
                return ResourceManager.GetString("FindFromDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flatten.
        /// </summary>
        public static string Flatten {
            get {
                return ResourceManager.GetString("Flatten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat VPK List.
        /// </summary>
        public static string FlatVpkList {
            get {
                return ResourceManager.GetString("FlatVpkList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Path.
        /// </summary>
        public static string GamePath {
            get {
                return ResourceManager.GetString("GamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the game path. Please set it manually. .
        /// </summary>
        public static string GamePathNotFoundMessage {
            get {
                return ResourceManager.GetString("GamePathNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the published file details..
        /// </summary>
        public static string GetPublishedFileDetailsProblemExplain {
            get {
                return ResourceManager.GetString("GetPublishedFileDetailsProblemExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Priority.
        /// </summary>
        public static string GlobalPriority {
            get {
                return ResourceManager.GetString("GlobalPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to download.
        /// </summary>
        public static string GoToDownload {
            get {
                return ResourceManager.GetString("GoToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Failed to get the title).
        /// </summary>
        public static string HintFailedGetTitle {
            get {
                return ResourceManager.GetString("HintFailedGetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Getting the title...).
        /// </summary>
        public static string HintGettingTitle {
            get {
                return ResourceManager.GetString("HintGettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (selected items).
        /// </summary>
        public static string HintSelectedItems {
            get {
                return ResourceManager.GetString("HintSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore All.
        /// </summary>
        public static string IgnoreAll {
            get {
                return ResourceManager.GetString("IgnoreAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Case.
        /// </summary>
        public static string IgnoreCase {
            get {
                return ResourceManager.GetString("IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Path: .
        /// </summary>
        public static string ImagePathColon {
            get {
                return ResourceManager.GetString("ImagePathColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import..
        /// </summary>
        public static string ImportErrorMessage {
            get {
                return ResourceManager.GetString("ImportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported successfully..
        /// </summary>
        public static string ImportSuccessMessage {
            get {
                return ResourceManager.GetString("ImportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import existing files to addon items..
        /// </summary>
        public static string ImportTip {
            get {
                return ResourceManager.GetString("ImportTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only enabled addons are included.
        /// </summary>
        public static string IncludeEnabledAddonsOnly {
            get {
                return ResourceManager.GetString("IncludeEnabledAddonsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include linked collections.
        /// </summary>
        public static string IncludeLinkedCollections {
            get {
                return ResourceManager.GetString("IncludeLinkedCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Name.
        /// </summary>
        public static string IncludeName {
            get {
                return ResourceManager.GetString("IncludeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include VPK Description.
        /// </summary>
        public static string IncludeVpkDescription {
            get {
                return ResourceManager.GetString("IncludeVpkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Workshop Description.
        /// </summary>
        public static string IncludeWorkshopDescription {
            get {
                return ResourceManager.GetString("IncludeWorkshopDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input cannot be empty..
        /// </summary>
        public static string InputCannotBeEmptyMessage {
            get {
                return ResourceManager.GetString("InputCannotBeEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input number or link.
        /// </summary>
        public static string InputPublishedFileIdHint {
            get {
                return ResourceManager.GetString("InputPublishedFileIdHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input the name of the tag: .
        /// </summary>
        public static string InputTagNameMessage {
            get {
                return ResourceManager.GetString("InputTagNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection id is invalid..
        /// </summary>
        public static string InvalidCollectionIdMessage {
            get {
                return ResourceManager.GetString("InvalidCollectionIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game path &quot;{0}&quot; is invalid..
        /// </summary>
        public static string InvalidGamePathMessage {
            get {
                return ResourceManager.GetString("InvalidGamePathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input..
        /// </summary>
        public static string InvalidInputMessage {
            get {
                return ResourceManager.GetString("InvalidInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target group is the subgroup of the source group..
        /// </summary>
        public static string InvalidMoveMessage {
            get {
                return ResourceManager.GetString("InvalidMoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid published file id..
        /// </summary>
        public static string InvalidPublishedFileIdMessage {
            get {
                return ResourceManager.GetString("InvalidPublishedFileIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item ID.
        /// </summary>
        public static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the item already exists..
        /// </summary>
        public static string ItemNameExists {
            get {
                return ResourceManager.GetString("ItemNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifetime Favorites: .
        /// </summary>
        public static string LifetimeFavoritesColon {
            get {
                return ResourceManager.GetString("LifetimeFavoritesColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifetime Subscriptions: .
        /// </summary>
        public static string LifetimeSubscriptionsColon {
            get {
                return ResourceManager.GetString("LifetimeSubscriptionsColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Addon.
        /// </summary>
        public static string MissingAddon {
            get {
                return ResourceManager.GetString("MissingAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Here.
        /// </summary>
        public static string MoveHere {
            get {
                return ResourceManager.GetString("MoveHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving: {0}.
        /// </summary>
        public static string MovingMessage {
            get {
                return ResourceManager.GetString("MovingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items are selected..
        /// </summary>
        public static string MultipleItemsSelected {
            get {
                return ResourceManager.GetString("MultipleItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Need Restart).
        /// </summary>
        public static string NeedRestartHint {
            get {
                return ResourceManager.GetString("NeedRestartHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tag.
        /// </summary>
        public static string NewTag {
            get {
                return ResourceManager.GetString("NewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available: {0}.
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available name.
        /// </summary>
        public static string NoAvailableName {
            get {
                return ResourceManager.GetString("NoAvailableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null.
        /// </summary>
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Directory.
        /// </summary>
        public static string OpenDirectory {
            get {
                return ResourceManager.GetString("OpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a directory where the addons are stored. .
        /// </summary>
        public static string OpenDirectoryTip {
            get {
                return ResourceManager.GetString("OpenDirectoryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Website.
        /// </summary>
        public static string OpenWebsite {
            get {
                return ResourceManager.GetString("OpenWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Workshop Page.
        /// </summary>
        public static string OpenWorkshopPage {
            get {
                return ResourceManager.GetString("OpenWorkshopPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Group: .
        /// </summary>
        public static string ParentGroupColon {
            get {
                return ResourceManager.GetString("ParentGroupColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path: .
        /// </summary>
        public static string PathColon {
            get {
                return ResourceManager.GetString("PathColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing....
        /// </summary>
        public static string PreparingMessage {
            get {
                return ResourceManager.GetString("PreparingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems.
        /// </summary>
        public static string Problems {
            get {
                return ResourceManager.GetString("Problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published File Details.
        /// </summary>
        public static string PublishedFileDetails {
            get {
                return ResourceManager.GetString("PublishedFileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        public static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push failed..
        /// </summary>
        public static string PushErrorMessage {
            get {
                return ResourceManager.GetString("PushErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push succeeded. If your game is running, go to the game menu to refresh addons..
        /// </summary>
        public static string PushSuccessMessage {
            get {
                return ResourceManager.GetString("PushSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push enablement states of all addons to the game..
        /// </summary>
        public static string PushTip {
            get {
                return ResourceManager.GetString("PushTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly Select.
        /// </summary>
        public static string RandomlySelect {
            get {
                return ResourceManager.GetString("RandomlySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly enable a child item in groups where the strategy of enablement is &quot;Random Single&quot;..
        /// </summary>
        public static string RandomlySelectTip {
            get {
                return ResourceManager.GetString("RandomlySelectTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing....
        /// </summary>
        public static string RefreshingHint {
            get {
                return ResourceManager.GetString("RefreshingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        public static string RemoveAll {
            get {
                return ResourceManager.GetString("RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Tag.
        /// </summary>
        public static string RenameTag {
            get {
                return ResourceManager.GetString("RenameTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do this, files will be retained..
        /// </summary>
        public static string RetainFileMessage {
            get {
                return ResourceManager.GetString("RetainFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string SearchingMessage {
            get {
                return ResourceManager.GetString("SearchingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the auto update strategy to Default recursively.
        /// </summary>
        public static string SetAutoUpdateStrategyToDefaultRecursively {
            get {
                return ResourceManager.GetString("SetAutoUpdateStrategyToDefaultRecursively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the auto update strategy to Disabled recursively.
        /// </summary>
        public static string SetAutoUpdateStrategyToDisabledRecursively {
            get {
                return ResourceManager.GetString("SetAutoUpdateStrategyToDisabledRecursively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the auto update strategy to Enabled recursively.
        /// </summary>
        public static string SetAutoUpdateStrategyToEnabledRecursively {
            get {
                return ResourceManager.GetString("SetAutoUpdateStrategyToEnabledRecursively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in File Explorer.
        /// </summary>
        public static string ShowInFileExplorer {
            get {
                return ResourceManager.GetString("ShowInFileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip All.
        /// </summary>
        public static string SkipAll {
            get {
                return ResourceManager.GetString("SkipAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions: .
        /// </summary>
        public static string SubscriptionsColon {
            get {
                return ResourceManager.GetString("SubscriptionsColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Editor.
        /// </summary>
        public static string TagEditor {
            get {
                return ResourceManager.GetString("TagEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Filter Mode.
        /// </summary>
        public static string TagFilterMode {
            get {
                return ResourceManager.GetString("TagFilterMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Manager.
        /// </summary>
        public static string TagManager {
            get {
                return ResourceManager.GetString("TagManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag name already exists..
        /// </summary>
        public static string TagNameExistMessage {
            get {
                return ResourceManager.GetString("TagNameExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags: .
        /// </summary>
        public static string TagsColon {
            get {
                return ResourceManager.GetString("TagsColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags of &quot;{0}&quot;.
        /// </summary>
        public static string TagsOf {
            get {
                return ResourceManager.GetString("TagsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This list is sorted by priority.
        /// </summary>
        public static string ThisListSortByPriorityMessage {
            get {
                return ResourceManager.GetString("ThisListSortByPriorityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string TitleColon {
            get {
                return ResourceManager.GetString("TitleColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed Group.
        /// </summary>
        public static string UnnamedGroup {
            get {
                return ResourceManager.GetString("UnnamedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed Workshop Addon.
        /// </summary>
        public static string UnnamedWorkshopAddon {
            get {
                return ResourceManager.GetString("UnnamedWorkshopAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Regex.
        /// </summary>
        public static string UseRegex {
            get {
                return ResourceManager.GetString("UseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string VersionColon {
            get {
                return ResourceManager.GetString("VersionColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views: .
        /// </summary>
        public static string ViewsColon {
            get {
                return ResourceManager.GetString("ViewsColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPK file conflicts found.  .
        /// </summary>
        public static string VpkAddonConflictProblemExplain {
            get {
                return ResourceManager.GetString("VpkAddonConflictProblemExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPK Conflict List.
        /// </summary>
        public static string VpkConflictList {
            get {
                return ResourceManager.GetString("VpkConflictList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPK Information.
        /// </summary>
        public static string VpkInfo {
            get {
                return ResourceManager.GetString("VpkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        public static string Workshop {
            get {
                return ResourceManager.GetString("Workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Addon.
        /// </summary>
        public static string WorkshopAddon {
            get {
                return ResourceManager.GetString("WorkshopAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Collection.
        /// </summary>
        public static string WorkshopCollection {
            get {
                return ResourceManager.GetString("WorkshopCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Item Auto Update.
        /// </summary>
        public static string WorkshopItemAutoUpdate {
            get {
                return ResourceManager.GetString("WorkshopItemAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} redundant VPK file(s) with a total size of {1} were found. Each addon&apos;s directory will retain only the latest VPK file. Are you sure you want to proceed? .
        /// </summary>
        public static string WorkshopVpkAddonDeleteRedundantVpkFilesReportConfirmMessage {
            get {
                return ResourceManager.GetString("WorkshopVpkAddonDeleteRedundantVpkFilesReportConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No redundant VPK files were found..
        /// </summary>
        public static string WorkshopVpkAddonDeleteRedundantVpkFilesReportEmptyMessage {
            get {
                return ResourceManager.GetString("WorkshopVpkAddonDeleteRedundantVpkFilesReportEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} redundant VPK file(s) with a total size of {1} have been deleted..
        /// </summary>
        public static string WorkshopVpkAddonDeleteRedundantVpkFilesReportSuccessMessage {
            get {
                return ResourceManager.GetString("WorkshopVpkAddonDeleteRedundantVpkFilesReportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workshop vpk file is not loaded. This problem will disappear once the download is completed successfully. If the download didn&apos;t start, you can press Check button to try to start the download..
        /// </summary>
        public static string WorkshopVpkFileNotLoadProblemExplain {
            get {
                return ResourceManager.GetString("WorkshopVpkFileNotLoadProblemExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop VPK Finder .
        /// </summary>
        public static string WorkshopVpkFinder {
            get {
                return ResourceManager.GetString("WorkshopVpkFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
