//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace L4D2AddonAssistant.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("L4D2AddonAssistant.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Abort 的本地化字符串。
        /// </summary>
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About L4D2AddonAssistant 的本地化字符串。
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There&apos;re problems in subitems. 的本地化字符串。
        /// </summary>
        public static string AddonChildProblemExplain {
            get {
                return ResourceManager.GetString("AddonChildProblemExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The corresponding file &quot;{0}&quot; doesn&apos;t exist. 的本地化字符串。
        /// </summary>
        public static string AddonFileNotExistProblemExplain {
            get {
                return ResourceManager.GetString("AddonFileNotExistProblemExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The strategy of enablement of the group is not applied correctly. 的本地化字符串。
        /// </summary>
        public static string AddonGroupEnableStrategyProblemExplain {
            get {
                return ResourceManager.GetString("AddonGroupEnableStrategyProblemExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The addon {0} denied the move or renaming. There may be ongoing tasks(like download tasks). Please try again later. 的本地化字符串。
        /// </summary>
        public static string AddonMoveDeniedMessage {
            get {
                return ResourceManager.GetString("AddonMoveDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A tool for managing Left 4 Dead 2 addons. 的本地化字符串。
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ascending 的本地化字符串。
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author: 的本地化字符串。
        /// </summary>
        public static string AuthorColon {
            get {
                return ResourceManager.GetString("AuthorColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is detected that you copied a workshop item link ({0}). Would you like to create a workshop addon? 的本地化字符串。
        /// </summary>
        public static string AutoDetectWorkshopItemLinkDialogMessage {
            get {
                return ResourceManager.GetString("AutoDetectWorkshopItemLinkDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto detect workshop item link in Clipboard 的本地化字符串。
        /// </summary>
        public static string AutoDetectWorkshopItemLinkInClipboard {
            get {
                return ResourceManager.GetString("AutoDetectWorkshopItemLinkInClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto redownload items 的本地化字符串。
        /// </summary>
        public static string AutoRedownload {
            get {
                return ResourceManager.GetString("AutoRedownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the Name Automatically 的本地化字符串。
        /// </summary>
        public static string AutoSetName {
            get {
                return ResourceManager.GetString("AutoSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Update Strategy 的本地化字符串。
        /// </summary>
        public static string AutoUpdateStrategy {
            get {
                return ResourceManager.GetString("AutoUpdateStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Move 的本地化字符串。
        /// </summary>
        public static string CancelMove {
            get {
                return ResourceManager.GetString("CancelMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Couldn&apos;t move the item &quot;{0}&quot;! 的本地化字符串。
        /// </summary>
        public static string CantMoveItemWithName {
            get {
                return ResourceManager.GetString("CantMoveItemWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check 的本地化字符串。
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check all addons to keep their status up to date. 的本地化字符串。
        /// </summary>
        public static string CheckAllTip {
            get {
                return ResourceManager.GetString("CheckAllTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for Updates 的本地化字符串。
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking for updates... 的本地化字符串。
        /// </summary>
        public static string CheckingForUpdatesMessage {
            get {
                return ResourceManager.GetString("CheckingForUpdatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear caches of all addons. 的本地化字符串。
        /// </summary>
        public static string ClearAllCachesTip {
            get {
                return ResourceManager.GetString("ClearAllCachesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Caches 的本地化字符串。
        /// </summary>
        public static string ClearCaches {
            get {
                return ResourceManager.GetString("ClearCaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collection ID 的本地化字符串。
        /// </summary>
        public static string CollectionId {
            get {
                return ResourceManager.GetString("CollectionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Delete 的本地化字符串。
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete the selected items? This cannot be undone.  的本地化字符串。
        /// </summary>
        public static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete the selected tags completely? 的本地化字符串。
        /// </summary>
        public static string ConfirmDeleteTagCompletely {
            get {
                return ResourceManager.GetString("ConfirmDeleteTagCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create the collection. Please try again. 的本地化字符串。
        /// </summary>
        public static string CreateCollectionFailedMessage {
            get {
                return ResourceManager.GetString("CreateCollectionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creation Time:  的本地化字符串。
        /// </summary>
        public static string CreationTimeColon {
            get {
                return ResourceManager.GetString("CreationTimeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current version is latest. 的本地化字符串。
        /// </summary>
        public static string CurrentVersionLatestMessage {
            get {
                return ResourceManager.GetString("CurrentVersionLatestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete And Retain Files 的本地化字符串。
        /// </summary>
        public static string DeleteAndRetainFile {
            get {
                return ResourceManager.GetString("DeleteAndRetainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Completely 的本地化字符串。
        /// </summary>
        public static string DeleteCompletely {
            get {
                return ResourceManager.GetString("DeleteCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Include tags in all addons) 的本地化字符串。
        /// </summary>
        public static string DeleteTagCompletelyTip {
            get {
                return ResourceManager.GetString("DeleteTagCompletelyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Descending 的本地化字符串。
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description: 的本地化字符串。
        /// </summary>
        public static string DescriptionColon {
            get {
                return ResourceManager.GetString("DescriptionColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Recursively (including all subitems) 的本地化字符串。
        /// </summary>
        public static string DisableRecursively {
            get {
                return ResourceManager.GetString("DisableRecursively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not open the directory &quot;left4dead2/addons&quot;. 的本地化字符串。
        /// </summary>
        public static string DontOpenGameAddonsDirectory {
            get {
                return ResourceManager.GetString("DontOpenGameAddonsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download List 的本地化字符串。
        /// </summary>
        public static string DownloadList {
            get {
                return ResourceManager.GetString("DownloadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled/Disabled 的本地化字符串。
        /// </summary>
        public static string EnabledOrDisabled {
            get {
                return ResourceManager.GetString("EnabledOrDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Recursively (including all subitems) 的本地化字符串。
        /// </summary>
        public static string EnableRecursively {
            get {
                return ResourceManager.GetString("EnableRecursively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strategy of Enablement 的本地化字符串。
        /// </summary>
        public static string EnableStrategy {
            get {
                return ResourceManager.GetString("EnableStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string Enum_AddonGroupEnableStrategy_All {
            get {
                return ResourceManager.GetString("Enum_AddonGroupEnableStrategy_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string Enum_AddonGroupEnableStrategy_None {
            get {
                return ResourceManager.GetString("Enum_AddonGroupEnableStrategy_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single 的本地化字符串。
        /// </summary>
        public static string Enum_AddonGroupEnableStrategy_Single {
            get {
                return ResourceManager.GetString("Enum_AddonGroupEnableStrategy_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random Single 的本地化字符串。
        /// </summary>
        public static string Enum_AddonGroupEnableStrategy_SingleRandom {
            get {
                return ResourceManager.GetString("Enum_AddonGroupEnableStrategy_SingleRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grid View 的本地化字符串。
        /// </summary>
        public static string Enum_AddonNodeListItemViewKind_Grid {
            get {
                return ResourceManager.GetString("Enum_AddonNodeListItemViewKind_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Large Tile View 的本地化字符串。
        /// </summary>
        public static string Enum_AddonNodeListItemViewKind_LargeTile {
            get {
                return ResourceManager.GetString("Enum_AddonNodeListItemViewKind_LargeTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile View 的本地化字符串。
        /// </summary>
        public static string Enum_AddonNodeListItemViewKind_MediumTile {
            get {
                return ResourceManager.GetString("Enum_AddonNodeListItemViewKind_MediumTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Small Tile View 的本地化字符串。
        /// </summary>
        public static string Enum_AddonNodeListItemViewKind_SmallTile {
            get {
                return ResourceManager.GetString("Enum_AddonNodeListItemViewKind_SmallTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort By Creation Time 的本地化字符串。
        /// </summary>
        public static string Enum_AddonNodeSortMethod_CreationTime {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Order 的本地化字符串。
        /// </summary>
        public static string Enum_AddonNodeSortMethod_Default {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort By State 的本地化字符串。
        /// </summary>
        public static string Enum_AddonNodeSortMethod_EnableState {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_EnableState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort By File Creation Time 的本地化字符串。
        /// </summary>
        public static string Enum_AddonNodeSortMethod_FileCreationTime {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_FileCreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort By File Size 的本地化字符串。
        /// </summary>
        public static string Enum_AddonNodeSortMethod_FileSize {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort By Name 的本地化字符串。
        /// </summary>
        public static string Enum_AddonNodeSortMethod_Name {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string Enum_AutoUpdateStrategy_Default {
            get {
                return ResourceManager.GetString("Enum_AutoUpdateStrategy_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string Enum_AutoUpdateStrategy_Disabled {
            get {
                return ResourceManager.GetString("Enum_AutoUpdateStrategy_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string Enum_AutoUpdateStrategy_Enabled {
            get {
                return ResourceManager.GetString("Enum_AutoUpdateStrategy_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception occurred during the operation! 的本地化字符串。
        /// </summary>
        public static string ExceptionOccurMessage {
            get {
                return ResourceManager.GetString("ExceptionOccurMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to retrieve the latest version. 的本地化字符串。
        /// </summary>
        public static string FailedToGetLatestVersion {
            get {
                return ResourceManager.GetString("FailedToGetLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Favorites:  的本地化字符串。
        /// </summary>
        public static string FavoritesColon {
            get {
                return ResourceManager.GetString("FavoritesColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file download is uncompleted! 的本地化字符串。
        /// </summary>
        public static string FileDownloadUncompleted {
            get {
                return ResourceManager.GetString("FileDownloadUncompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Size:  的本地化字符串。
        /// </summary>
        public static string FileSizeColon {
            get {
                return ResourceManager.GetString("FileSizeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flatten 的本地化字符串。
        /// </summary>
        public static string Flatten {
            get {
                return ResourceManager.GetString("Flatten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flat VPK List 的本地化字符串。
        /// </summary>
        public static string FlatVpkList {
            get {
                return ResourceManager.GetString("FlatVpkList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Path 的本地化字符串。
        /// </summary>
        public static string GamePath {
            get {
                return ResourceManager.GetString("GamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get the published file details. 的本地化字符串。
        /// </summary>
        public static string GetPublishedFileDetailsProblemExplain {
            get {
                return ResourceManager.GetString("GetPublishedFileDetailsProblemExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to download 的本地化字符串。
        /// </summary>
        public static string GoToDownload {
            get {
                return ResourceManager.GetString("GoToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group 的本地化字符串。
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore 的本地化字符串。
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore Case 的本地化字符串。
        /// </summary>
        public static string IgnoreCase {
            get {
                return ResourceManager.GetString("IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to import. 的本地化字符串。
        /// </summary>
        public static string ImportErrorMessage {
            get {
                return ResourceManager.GetString("ImportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imported successfully. 的本地化字符串。
        /// </summary>
        public static string ImportSuccessMessage {
            get {
                return ResourceManager.GetString("ImportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import existing files to addon items. 的本地化字符串。
        /// </summary>
        public static string ImportTip {
            get {
                return ResourceManager.GetString("ImportTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only enabled addons are included 的本地化字符串。
        /// </summary>
        public static string IncludeEnabledAddonsOnly {
            get {
                return ResourceManager.GetString("IncludeEnabledAddonsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include linked collections 的本地化字符串。
        /// </summary>
        public static string IncludeLinkedCollections {
            get {
                return ResourceManager.GetString("IncludeLinkedCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include Name 的本地化字符串。
        /// </summary>
        public static string IncludeName {
            get {
                return ResourceManager.GetString("IncludeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include VPK Description 的本地化字符串。
        /// </summary>
        public static string IncludeVpkDescription {
            get {
                return ResourceManager.GetString("IncludeVpkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include Workshop Description 的本地化字符串。
        /// </summary>
        public static string IncludeWorkshopDescription {
            get {
                return ResourceManager.GetString("IncludeWorkshopDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The input cannot be empty. 的本地化字符串。
        /// </summary>
        public static string InputCannotBeEmptyMessage {
            get {
                return ResourceManager.GetString("InputCannotBeEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input number or link 的本地化字符串。
        /// </summary>
        public static string InputPublishedFileIdHint {
            get {
                return ResourceManager.GetString("InputPublishedFileIdHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input the name of the tag:  的本地化字符串。
        /// </summary>
        public static string InputTagNameMessage {
            get {
                return ResourceManager.GetString("InputTagNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The collection id is invalid. 的本地化字符串。
        /// </summary>
        public static string InvalidCollectionIdMessage {
            get {
                return ResourceManager.GetString("InvalidCollectionIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The game path &quot;{0}&quot; is invalid. 的本地化字符串。
        /// </summary>
        public static string InvalidGamePathMessage {
            get {
                return ResourceManager.GetString("InvalidGamePathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid input. 的本地化字符串。
        /// </summary>
        public static string InvalidInputMessage {
            get {
                return ResourceManager.GetString("InvalidInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The target group is the subgroup of the source group. 的本地化字符串。
        /// </summary>
        public static string InvalidMoveMessage {
            get {
                return ResourceManager.GetString("InvalidMoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid published file id. 的本地化字符串。
        /// </summary>
        public static string InvalidPublishedFileIdMessage {
            get {
                return ResourceManager.GetString("InvalidPublishedFileIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item ID 的本地化字符串。
        /// </summary>
        public static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name of the item already exists. 的本地化字符串。
        /// </summary>
        public static string ItemNameExists {
            get {
                return ResourceManager.GetString("ItemNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lifetime Favorites:  的本地化字符串。
        /// </summary>
        public static string LifetimeFavoritesColon {
            get {
                return ResourceManager.GetString("LifetimeFavoritesColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lifetime Subscriptions:  的本地化字符串。
        /// </summary>
        public static string LifetimeSubscriptionsColon {
            get {
                return ResourceManager.GetString("LifetimeSubscriptionsColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move 的本地化字符串。
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Down 的本地化字符串。
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Here 的本地化字符串。
        /// </summary>
        public static string MoveHere {
            get {
                return ResourceManager.GetString("MoveHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Up 的本地化字符串。
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moving: {0} 的本地化字符串。
        /// </summary>
        public static string MovingMessage {
            get {
                return ResourceManager.GetString("MovingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} items are selected. 的本地化字符串。
        /// </summary>
        public static string MultipleItemsSelected {
            get {
                return ResourceManager.GetString("MultipleItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  (Need Restart) 的本地化字符串。
        /// </summary>
        public static string NeedRestartHint {
            get {
                return ResourceManager.GetString("NeedRestartHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Tag 的本地化字符串。
        /// </summary>
        public static string NewTag {
            get {
                return ResourceManager.GetString("NewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New version available: {0} 的本地化字符串。
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No available name 的本地化字符串。
        /// </summary>
        public static string NoAvailableName {
            get {
                return ResourceManager.GetString("NoAvailableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Null 的本地化字符串。
        /// </summary>
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open a directory where the addons are stored.  的本地化字符串。
        /// </summary>
        public static string OpenDirectoryTip {
            get {
                return ResourceManager.GetString("OpenDirectoryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Workshop Page 的本地化字符串。
        /// </summary>
        public static string OpenWorkshopPage {
            get {
                return ResourceManager.GetString("OpenWorkshopPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operations 的本地化字符串。
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preparing... 的本地化字符串。
        /// </summary>
        public static string PreparingMessage {
            get {
                return ResourceManager.GetString("PreparingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Priority 的本地化字符串。
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Problems 的本地化字符串。
        /// </summary>
        public static string Problems {
            get {
                return ResourceManager.GetString("Problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Published File Details 的本地化字符串。
        /// </summary>
        public static string PublishedFileDetails {
            get {
                return ResourceManager.GetString("PublishedFileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Push 的本地化字符串。
        /// </summary>
        public static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Push failed. 的本地化字符串。
        /// </summary>
        public static string PushErrorMessage {
            get {
                return ResourceManager.GetString("PushErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Push succeeded. If your game is running, go to the game menu to refresh addons. 的本地化字符串。
        /// </summary>
        public static string PushSuccessMessage {
            get {
                return ResourceManager.GetString("PushSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Push enablement states of all addons to the game. 的本地化字符串。
        /// </summary>
        public static string PushTip {
            get {
                return ResourceManager.GetString("PushTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Randomly Select 的本地化字符串。
        /// </summary>
        public static string RandomlySelect {
            get {
                return ResourceManager.GetString("RandomlySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Randomly enable a child item in groups where the strategy of enablement is &quot;Random Single&quot;. 的本地化字符串。
        /// </summary>
        public static string RandomlySelectTip {
            get {
                return ResourceManager.GetString("RandomlySelectTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename 的本地化字符串。
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename Tag 的本地化字符串。
        /// </summary>
        public static string RenameTag {
            get {
                return ResourceManager.GetString("RenameTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resume 的本地化字符串。
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you do this, files will be retained. 的本地化字符串。
        /// </summary>
        public static string RetainFileMessage {
            get {
                return ResourceManager.GetString("RetainFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searching... 的本地化字符串。
        /// </summary>
        public static string SearchingMessage {
            get {
                return ResourceManager.GetString("SearchingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show in File Explorer 的本地化字符串。
        /// </summary>
        public static string ShowInFileExplorer {
            get {
                return ResourceManager.GetString("ShowInFileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip 的本地化字符串。
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip All 的本地化字符串。
        /// </summary>
        public static string SkipAll {
            get {
                return ResourceManager.GetString("SkipAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscriptions:  的本地化字符串。
        /// </summary>
        public static string SubscriptionsColon {
            get {
                return ResourceManager.GetString("SubscriptionsColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag Manager 的本地化字符串。
        /// </summary>
        public static string TagManager {
            get {
                return ResourceManager.GetString("TagManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The tag name already exists. 的本地化字符串。
        /// </summary>
        public static string TagNameExistMessage {
            get {
                return ResourceManager.GetString("TagNameExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This list is sorted by priority 的本地化字符串。
        /// </summary>
        public static string ThisListSortByPriorityMessage {
            get {
                return ResourceManager.GetString("ThisListSortByPriorityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title: 的本地化字符串。
        /// </summary>
        public static string TitleColon {
            get {
                return ResourceManager.GetString("TitleColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unnamed Group 的本地化字符串。
        /// </summary>
        public static string UnnamedGroup {
            get {
                return ResourceManager.GetString("UnnamedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unnamed Workshop Addon 的本地化字符串。
        /// </summary>
        public static string UnnamedWorkshopAddon {
            get {
                return ResourceManager.GetString("UnnamedWorkshopAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Regex 的本地化字符串。
        /// </summary>
        public static string UseRegex {
            get {
                return ResourceManager.GetString("UseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: 的本地化字符串。
        /// </summary>
        public static string VersionColon {
            get {
                return ResourceManager.GetString("VersionColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Views:  的本地化字符串。
        /// </summary>
        public static string ViewsColon {
            get {
                return ResourceManager.GetString("ViewsColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VPK Information 的本地化字符串。
        /// </summary>
        public static string VpkInfo {
            get {
                return ResourceManager.GetString("VpkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workshop 的本地化字符串。
        /// </summary>
        public static string Workshop {
            get {
                return ResourceManager.GetString("Workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workshop Addon 的本地化字符串。
        /// </summary>
        public static string WorkshopAddon {
            get {
                return ResourceManager.GetString("WorkshopAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workshop Collection 的本地化字符串。
        /// </summary>
        public static string WorkshopCollection {
            get {
                return ResourceManager.GetString("WorkshopCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workshop Item Auto Update 的本地化字符串。
        /// </summary>
        public static string WorkshopItemAutoUpdate {
            get {
                return ResourceManager.GetString("WorkshopItemAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The workshop vpk file is not loaded. 的本地化字符串。
        /// </summary>
        public static string WorkshopVpkFileNotLoadProblemExplain {
            get {
                return ResourceManager.GetString("WorkshopVpkFileNotLoadProblemExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
