//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace L4D2AddonAssistant.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("L4D2AddonAssistant.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Abort 的本地化字符串。
        /// </summary>
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author: 的本地化字符串。
        /// </summary>
        public static string AuthorColon {
            get {
                return ResourceManager.GetString("AuthorColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Update Strategy 的本地化字符串。
        /// </summary>
        public static string AutoUpdateStrategy {
            get {
                return ResourceManager.GetString("AutoUpdateStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Move 的本地化字符串。
        /// </summary>
        public static string CancelMove {
            get {
                return ResourceManager.GetString("CancelMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Couldn&apos;t move the item &quot;{0}&quot;! 的本地化字符串。
        /// </summary>
        public static string CantMoveItemWithName {
            get {
                return ResourceManager.GetString("CantMoveItemWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Delete 的本地化字符串。
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete the selected items? This cannot be undone.  的本地化字符串。
        /// </summary>
        public static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete And Retain Files 的本地化字符串。
        /// </summary>
        public static string DeleteAndRetainFile {
            get {
                return ResourceManager.GetString("DeleteAndRetainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description: 的本地化字符串。
        /// </summary>
        public static string DescriptionColon {
            get {
                return ResourceManager.GetString("DescriptionColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Recursively (including all subitems) 的本地化字符串。
        /// </summary>
        public static string DisableRecursively {
            get {
                return ResourceManager.GetString("DisableRecursively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Recursively (including all subitems) 的本地化字符串。
        /// </summary>
        public static string EnableRecursively {
            get {
                return ResourceManager.GetString("EnableRecursively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strategy of Enablement 的本地化字符串。
        /// </summary>
        public static string EnableStrategy {
            get {
                return ResourceManager.GetString("EnableStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string Enum_AddonGroupEnableStrategy_All {
            get {
                return ResourceManager.GetString("Enum_AddonGroupEnableStrategy_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string Enum_AddonGroupEnableStrategy_None {
            get {
                return ResourceManager.GetString("Enum_AddonGroupEnableStrategy_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single 的本地化字符串。
        /// </summary>
        public static string Enum_AddonGroupEnableStrategy_Single {
            get {
                return ResourceManager.GetString("Enum_AddonGroupEnableStrategy_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random Single 的本地化字符串。
        /// </summary>
        public static string Enum_AddonGroupEnableStrategy_SingleRandom {
            get {
                return ResourceManager.GetString("Enum_AddonGroupEnableStrategy_SingleRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string Enum_AutoUpdateStrategy_Default {
            get {
                return ResourceManager.GetString("Enum_AutoUpdateStrategy_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string Enum_AutoUpdateStrategy_Disabled {
            get {
                return ResourceManager.GetString("Enum_AutoUpdateStrategy_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string Enum_AutoUpdateStrategy_Enabled {
            get {
                return ResourceManager.GetString("Enum_AutoUpdateStrategy_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception occurred during the operation! 的本地化字符串。
        /// </summary>
        public static string ExceptionOccurMessage {
            get {
                return ResourceManager.GetString("ExceptionOccurMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Path 的本地化字符串。
        /// </summary>
        public static string GamePath {
            get {
                return ResourceManager.GetString("GamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group 的本地化字符串。
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to import. 的本地化字符串。
        /// </summary>
        public static string ImportErrorMessage {
            get {
                return ResourceManager.GetString("ImportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imported successfully. 的本地化字符串。
        /// </summary>
        public static string ImportSuccessMessage {
            get {
                return ResourceManager.GetString("ImportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The game path &quot;{0}&quot; is invalid. 的本地化字符串。
        /// </summary>
        public static string InvalidGamePathMessage {
            get {
                return ResourceManager.GetString("InvalidGamePathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid input. 的本地化字符串。
        /// </summary>
        public static string InvalidInputMessage {
            get {
                return ResourceManager.GetString("InvalidInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The target group is the subgroup of the source group. 的本地化字符串。
        /// </summary>
        public static string InvalidMoveMessage {
            get {
                return ResourceManager.GetString("InvalidMoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item ID 的本地化字符串。
        /// </summary>
        public static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name of the item already exists. 的本地化字符串。
        /// </summary>
        public static string ItemNameExists {
            get {
                return ResourceManager.GetString("ItemNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move 的本地化字符串。
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Here 的本地化字符串。
        /// </summary>
        public static string MoveHere {
            get {
                return ResourceManager.GetString("MoveHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} items are selected. 的本地化字符串。
        /// </summary>
        public static string MultipleItemsSelected {
            get {
                return ResourceManager.GetString("MultipleItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Null 的本地化字符串。
        /// </summary>
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ok 的本地化字符串。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operations 的本地化字符串。
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preparing... 的本地化字符串。
        /// </summary>
        public static string PreparingMessage {
            get {
                return ResourceManager.GetString("PreparingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Push 的本地化字符串。
        /// </summary>
        public static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Push failed. 的本地化字符串。
        /// </summary>
        public static string PushErrorMessage {
            get {
                return ResourceManager.GetString("PushErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Push succeeded. 的本地化字符串。
        /// </summary>
        public static string PushSuccessMessage {
            get {
                return ResourceManager.GetString("PushSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you do this, files will be retained. 的本地化字符串。
        /// </summary>
        public static string RetainFileMessage {
            get {
                return ResourceManager.GetString("RetainFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip 的本地化字符串。
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip All 的本地化字符串。
        /// </summary>
        public static string SkipAll {
            get {
                return ResourceManager.GetString("SkipAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title: 的本地化字符串。
        /// </summary>
        public static string TitleColon {
            get {
                return ResourceManager.GetString("TitleColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unnamed Group 的本地化字符串。
        /// </summary>
        public static string UnnamedGroup {
            get {
                return ResourceManager.GetString("UnnamedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unnamed Workshop Addon 的本地化字符串。
        /// </summary>
        public static string UnnamedWorkshopAddon {
            get {
                return ResourceManager.GetString("UnnamedWorkshopAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: 的本地化字符串。
        /// </summary>
        public static string VersionColon {
            get {
                return ResourceManager.GetString("VersionColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VPK Information 的本地化字符串。
        /// </summary>
        public static string VpkInfo {
            get {
                return ResourceManager.GetString("VpkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workshop 的本地化字符串。
        /// </summary>
        public static string Workshop {
            get {
                return ResourceManager.GetString("Workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workshop Addon 的本地化字符串。
        /// </summary>
        public static string WorkshopAddon {
            get {
                return ResourceManager.GetString("WorkshopAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
