//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace L4D2AddonAssistant.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("L4D2AddonAssistant.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Abort 的本地化字符串。
        /// </summary>
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About L4D2AddonAssistant 的本地化字符串。
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The addon {0} denied the move or renaming. There may be ongoing tasks. Please try again later. 的本地化字符串。
        /// </summary>
        public static string AddonMoveDeniedMessage {
            get {
                return ResourceManager.GetString("AddonMoveDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A tool for managing Left 4 Dead 2 addons. 的本地化字符串。
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ascending 的本地化字符串。
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author: 的本地化字符串。
        /// </summary>
        public static string AuthorColon {
            get {
                return ResourceManager.GetString("AuthorColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the name automatically 的本地化字符串。
        /// </summary>
        public static string AutoSetName {
            get {
                return ResourceManager.GetString("AutoSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Update Strategy 的本地化字符串。
        /// </summary>
        public static string AutoUpdateStrategy {
            get {
                return ResourceManager.GetString("AutoUpdateStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Move 的本地化字符串。
        /// </summary>
        public static string CancelMove {
            get {
                return ResourceManager.GetString("CancelMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Couldn&apos;t move the item &quot;{0}&quot;! 的本地化字符串。
        /// </summary>
        public static string CantMoveItemWithName {
            get {
                return ResourceManager.GetString("CantMoveItemWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check 的本地化字符串。
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check all addons to keep their status up to date. 的本地化字符串。
        /// </summary>
        public static string CheckAllTip {
            get {
                return ResourceManager.GetString("CheckAllTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear caches of all addons. 的本地化字符串。
        /// </summary>
        public static string ClearAllCachesTip {
            get {
                return ResourceManager.GetString("ClearAllCachesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Caches 的本地化字符串。
        /// </summary>
        public static string ClearCaches {
            get {
                return ResourceManager.GetString("ClearCaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Delete 的本地化字符串。
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete the selected items? This cannot be undone.  的本地化字符串。
        /// </summary>
        public static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete And Retain Files 的本地化字符串。
        /// </summary>
        public static string DeleteAndRetainFile {
            get {
                return ResourceManager.GetString("DeleteAndRetainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Descending 的本地化字符串。
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description: 的本地化字符串。
        /// </summary>
        public static string DescriptionColon {
            get {
                return ResourceManager.GetString("DescriptionColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Recursively (including all subitems) 的本地化字符串。
        /// </summary>
        public static string DisableRecursively {
            get {
                return ResourceManager.GetString("DisableRecursively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Recursively (including all subitems) 的本地化字符串。
        /// </summary>
        public static string EnableRecursively {
            get {
                return ResourceManager.GetString("EnableRecursively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strategy of Enablement 的本地化字符串。
        /// </summary>
        public static string EnableStrategy {
            get {
                return ResourceManager.GetString("EnableStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string Enum_AddonGroupEnableStrategy_All {
            get {
                return ResourceManager.GetString("Enum_AddonGroupEnableStrategy_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string Enum_AddonGroupEnableStrategy_None {
            get {
                return ResourceManager.GetString("Enum_AddonGroupEnableStrategy_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single 的本地化字符串。
        /// </summary>
        public static string Enum_AddonGroupEnableStrategy_Single {
            get {
                return ResourceManager.GetString("Enum_AddonGroupEnableStrategy_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random Single 的本地化字符串。
        /// </summary>
        public static string Enum_AddonGroupEnableStrategy_SingleRandom {
            get {
                return ResourceManager.GetString("Enum_AddonGroupEnableStrategy_SingleRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grid View 的本地化字符串。
        /// </summary>
        public static string Enum_AddonNodeListItemViewKind_Grid {
            get {
                return ResourceManager.GetString("Enum_AddonNodeListItemViewKind_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Large Tile View 的本地化字符串。
        /// </summary>
        public static string Enum_AddonNodeListItemViewKind_LargeTile {
            get {
                return ResourceManager.GetString("Enum_AddonNodeListItemViewKind_LargeTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile View 的本地化字符串。
        /// </summary>
        public static string Enum_AddonNodeListItemViewKind_MediumTile {
            get {
                return ResourceManager.GetString("Enum_AddonNodeListItemViewKind_MediumTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Small Tile View 的本地化字符串。
        /// </summary>
        public static string Enum_AddonNodeListItemViewKind_SmallTile {
            get {
                return ResourceManager.GetString("Enum_AddonNodeListItemViewKind_SmallTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Order 的本地化字符串。
        /// </summary>
        public static string Enum_AddonNodeSortMethod_Default {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort By State 的本地化字符串。
        /// </summary>
        public static string Enum_AddonNodeSortMethod_EnableState {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_EnableState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort By File Size 的本地化字符串。
        /// </summary>
        public static string Enum_AddonNodeSortMethod_FileSize {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort By Name 的本地化字符串。
        /// </summary>
        public static string Enum_AddonNodeSortMethod_Name {
            get {
                return ResourceManager.GetString("Enum_AddonNodeSortMethod_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string Enum_AutoUpdateStrategy_Default {
            get {
                return ResourceManager.GetString("Enum_AutoUpdateStrategy_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string Enum_AutoUpdateStrategy_Disabled {
            get {
                return ResourceManager.GetString("Enum_AutoUpdateStrategy_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string Enum_AutoUpdateStrategy_Enabled {
            get {
                return ResourceManager.GetString("Enum_AutoUpdateStrategy_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception occurred during the operation! 的本地化字符串。
        /// </summary>
        public static string ExceptionOccurMessage {
            get {
                return ResourceManager.GetString("ExceptionOccurMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Favorites:  的本地化字符串。
        /// </summary>
        public static string FavoritesColon {
            get {
                return ResourceManager.GetString("FavoritesColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Size:  的本地化字符串。
        /// </summary>
        public static string FileSizeColon {
            get {
                return ResourceManager.GetString("FileSizeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flatten 的本地化字符串。
        /// </summary>
        public static string Flatten {
            get {
                return ResourceManager.GetString("Flatten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Path 的本地化字符串。
        /// </summary>
        public static string GamePath {
            get {
                return ResourceManager.GetString("GamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group 的本地化字符串。
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore Case 的本地化字符串。
        /// </summary>
        public static string IgnoreCase {
            get {
                return ResourceManager.GetString("IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to import. 的本地化字符串。
        /// </summary>
        public static string ImportErrorMessage {
            get {
                return ResourceManager.GetString("ImportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imported successfully. 的本地化字符串。
        /// </summary>
        public static string ImportSuccessMessage {
            get {
                return ResourceManager.GetString("ImportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import existing files to addon items. 的本地化字符串。
        /// </summary>
        public static string ImportTip {
            get {
                return ResourceManager.GetString("ImportTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include Name 的本地化字符串。
        /// </summary>
        public static string IncludeName {
            get {
                return ResourceManager.GetString("IncludeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include VPK Description 的本地化字符串。
        /// </summary>
        public static string IncludeVpkDescription {
            get {
                return ResourceManager.GetString("IncludeVpkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include Workshop Description 的本地化字符串。
        /// </summary>
        public static string IncludeWorkshopDescription {
            get {
                return ResourceManager.GetString("IncludeWorkshopDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input number or link 的本地化字符串。
        /// </summary>
        public static string InputPublishedFileIdHint {
            get {
                return ResourceManager.GetString("InputPublishedFileIdHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The game path &quot;{0}&quot; is invalid. 的本地化字符串。
        /// </summary>
        public static string InvalidGamePathMessage {
            get {
                return ResourceManager.GetString("InvalidGamePathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid input. 的本地化字符串。
        /// </summary>
        public static string InvalidInputMessage {
            get {
                return ResourceManager.GetString("InvalidInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The target group is the subgroup of the source group. 的本地化字符串。
        /// </summary>
        public static string InvalidMoveMessage {
            get {
                return ResourceManager.GetString("InvalidMoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item ID 的本地化字符串。
        /// </summary>
        public static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name of the item already exists. 的本地化字符串。
        /// </summary>
        public static string ItemNameExists {
            get {
                return ResourceManager.GetString("ItemNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lifetime Favorites:  的本地化字符串。
        /// </summary>
        public static string LifetimeFavoritesColon {
            get {
                return ResourceManager.GetString("LifetimeFavoritesColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lifetime Subscriptions:  的本地化字符串。
        /// </summary>
        public static string LifetimeSubscriptionsColon {
            get {
                return ResourceManager.GetString("LifetimeSubscriptionsColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move 的本地化字符串。
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Here 的本地化字符串。
        /// </summary>
        public static string MoveHere {
            get {
                return ResourceManager.GetString("MoveHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} items are selected. 的本地化字符串。
        /// </summary>
        public static string MultipleItemsSelected {
            get {
                return ResourceManager.GetString("MultipleItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  (Need Restart) 的本地化字符串。
        /// </summary>
        public static string NeedRestartHint {
            get {
                return ResourceManager.GetString("NeedRestartHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No available name 的本地化字符串。
        /// </summary>
        public static string NoAvailableName {
            get {
                return ResourceManager.GetString("NoAvailableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Null 的本地化字符串。
        /// </summary>
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open a directory where the addons are stored.  的本地化字符串。
        /// </summary>
        public static string OpenDirectoryTip {
            get {
                return ResourceManager.GetString("OpenDirectoryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operations 的本地化字符串。
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preparing... 的本地化字符串。
        /// </summary>
        public static string PreparingMessage {
            get {
                return ResourceManager.GetString("PreparingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Published File Details 的本地化字符串。
        /// </summary>
        public static string PublishedFileDetails {
            get {
                return ResourceManager.GetString("PublishedFileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Push 的本地化字符串。
        /// </summary>
        public static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Push failed. 的本地化字符串。
        /// </summary>
        public static string PushErrorMessage {
            get {
                return ResourceManager.GetString("PushErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Push succeeded. If your game is running, go to the game menu to refresh addons. 的本地化字符串。
        /// </summary>
        public static string PushSuccessMessage {
            get {
                return ResourceManager.GetString("PushSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Push enablement states of all addons to the game. 的本地化字符串。
        /// </summary>
        public static string PushTip {
            get {
                return ResourceManager.GetString("PushTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you do this, files will be retained. 的本地化字符串。
        /// </summary>
        public static string RetainFileMessage {
            get {
                return ResourceManager.GetString("RetainFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searching... 的本地化字符串。
        /// </summary>
        public static string SearchingMessage {
            get {
                return ResourceManager.GetString("SearchingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip 的本地化字符串。
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip All 的本地化字符串。
        /// </summary>
        public static string SkipAll {
            get {
                return ResourceManager.GetString("SkipAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscriptions:  的本地化字符串。
        /// </summary>
        public static string SubscriptionsColon {
            get {
                return ResourceManager.GetString("SubscriptionsColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title: 的本地化字符串。
        /// </summary>
        public static string TitleColon {
            get {
                return ResourceManager.GetString("TitleColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unnamed Group 的本地化字符串。
        /// </summary>
        public static string UnnamedGroup {
            get {
                return ResourceManager.GetString("UnnamedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unnamed Workshop Addon 的本地化字符串。
        /// </summary>
        public static string UnnamedWorkshopAddon {
            get {
                return ResourceManager.GetString("UnnamedWorkshopAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Regex 的本地化字符串。
        /// </summary>
        public static string UseRegex {
            get {
                return ResourceManager.GetString("UseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: 的本地化字符串。
        /// </summary>
        public static string VersionColon {
            get {
                return ResourceManager.GetString("VersionColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Views:  的本地化字符串。
        /// </summary>
        public static string ViewsColon {
            get {
                return ResourceManager.GetString("ViewsColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VPK Information 的本地化字符串。
        /// </summary>
        public static string VpkInfo {
            get {
                return ResourceManager.GetString("VpkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workshop 的本地化字符串。
        /// </summary>
        public static string Workshop {
            get {
                return ResourceManager.GetString("Workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workshop Addon 的本地化字符串。
        /// </summary>
        public static string WorkshopAddon {
            get {
                return ResourceManager.GetString("WorkshopAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workshop Item Auto Update 的本地化字符串。
        /// </summary>
        public static string WorkshopItemAutoUpdate {
            get {
                return ResourceManager.GetString("WorkshopItemAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
